modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"
issueTrackerURL = "${mod_tracker}"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
displayURL = "${mod_url}"
logoFile = "${mod_id}.png"
credits = "${mod_credits}"
authors = "${mod_authors}"
description = '''${mod_description}'''
#enumExtensions = "META-INF/enumextensions.json"

[[dependencies.${mod_id}]]
modId = "neoforge"
type = "required"
versionRange = "${neo_version_range}"
ordering = "NONE"
side = "BOTH"
[[dependencies.${mod_id}]]
modId = "minecraft"
type = "required"
versionRange="${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"
[[dependencies.${mod_id}]]
modId = "zenith"
type = "required" #mandatory
versionRange = "[${zenith_version},)"
ordering = "NONE"
side = "BOTH"
[[dependencies.${mod_id}]]
modId = "aether"
type = "required" #mandatory
versionRange = "[${aether_version},)"
ordering = "AFTER"
side = "BOTH"
[[dependencies.${mod_id}]]
modId = "aeroblender"
type = "required" #mandatory
versionRange = "[0,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "${mod_id}.mixins.json"